from typing import Protocol, Optional, Dict


class ClientRepoInterface(Protocol):
    """Abstract interface for the runtime container client registry."""

    def add_client(self, name: str, ip: str) -> None: ...
    def remove_client(self, name: str) -> None: ...
    def get_client(self, name: str) -> Optional[dict]: ...
    def list_clients(self) -> Dict[str, dict]: ...
    def contains(self, name: str) -> bool: ...
