from typing import Protocol, Any, List


class ContainerRuntimeRepoInterface(Protocol):
    """Abstract interface for container runtime operations (e.g., Docker)."""

    def get_container(self, name: str) -> Any: ...
    def list_containers(self, **kwargs) -> List[Any]: ...
    def create_container(self, **kwargs) -> Any: ...
    def pull_image(self, image_name: str) -> None: ...
    def get_image(self, image_name: str) -> Any: ...
    def get_network(self, name: str) -> Any: ...
    def list_networks(self) -> List[Any]: ...
    def create_network(self, **kwargs) -> Any: ...
    def get_volume(self, name: str) -> Any: ...
    def get_api_version(self) -> str: ...
    def create_endpoint_config(self, version: str, **kwargs) -> Any: ...
    def create_ipam_pool(self, **kwargs) -> Any: ...
    def create_ipam_config(self, pool_configs: list) -> Any: ...
    def create_ulimit(self, name: str, soft: int, hard: int) -> Any: ...
