from typing import Protocol, Any, Dict, List, Optional


class ContainerRuntimeRepoInterface(Protocol):
    """Abstract interface for container runtime operations (e.g., Docker)."""

    def get_container(self, name: str) -> Any: ...
    def list_containers(self, **kwargs) -> List[Any]: ...
    def create_container(self, **kwargs) -> Any: ...
    def pull_image(self, image_name: str) -> None: ...
    def get_image(self, image_name: str) -> Any: ...
    def get_network(self, name: str) -> Any: ...
    def list_networks(self) -> List[Any]: ...
    def create_network(self, **kwargs) -> Any: ...
    def get_volume(self, name: str) -> Any: ...
    def get_api_version(self) -> str: ...
    def create_endpoint_config(self, version: str, **kwargs) -> Any: ...
    def create_ipam_pool(self, **kwargs) -> Any: ...
    def create_ipam_config(self, pool_configs: list) -> Any: ...
    def create_ulimit(self, name: str, soft: int, hard: int) -> Any: ...
    def get_or_create_macvlan_network(
        self,
        parent_interface: str,
        parent_subnet: Optional[str] = None,
        parent_gateway: Optional[str] = None,
        interface_cache: Any = None,
    ) -> Any: ...
    def create_internal_network(self, container_name: str) -> Any: ...
    def get_existing_mac_addresses_on_interface(
        self, parent_interface: str
    ) -> Dict[str, str]: ...
