from typing import Protocol, Optional, Tuple, Dict


class NetworkInterfaceCacheRepoInterface(Protocol):
    """Abstract interface for the network interface discovery cache."""

    def get_interface_type(self, interface_name: str) -> str: ...
    def get_interface_network(
        self, parent_interface: str
    ) -> Tuple[Optional[str], Optional[str]]: ...
    def get_all_interfaces(self) -> Dict[str, dict]: ...
    def set_interface(self, name: str, data: dict) -> None: ...
    def remove_interface(self, name: str) -> None: ...
