from typing import Protocol, Optional


class SerialRepoInterface(Protocol):
    """Abstract interface for serial port configuration persistence."""

    def save_configs(self, container_name: str, serial_configs: list) -> None: ...
    def load_configs(self, container_name: Optional[str] = None) -> dict: ...
    def delete_configs(self, container_name: str) -> None: ...
    def update_status(
        self, container_name: str, port_name: str, status: str, **kwargs
    ) -> None: ...
    def get_by_device_id(self, device_id: str) -> list: ...
    def get_all_configured_ports(self) -> list: ...
