from typing import Protocol


class VNICRepoInterface(Protocol):
    """Abstract interface for vNIC configuration persistence."""

    def save_configs(self, container_name: str, vnic_configs: list) -> None: ...
    def load_all_configs(self) -> dict: ...
    def load_configs(self, container_name: str) -> list: ...
    def delete_configs(self, container_name: str) -> None: ...
